AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0.1

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false  

Layout/LineLength:
  Max: 120

Layout/EndOfLine:
  Enabled: false

Lint/ScriptPermission:
  Enabled: false

Style/RedundantPercentQ:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
