AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**'
    - '*.gemspec'
  
Style/Documentation:
  Enabled: false
  
Gemspec/RequiredRubyVersion:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/RedundantPercentQ:
  Enabled: false